# a_tensor_initialization.py

In [1]:
import torch

In [2]:
t1 = torch.Tensor([1, 2, 3], device='cpu')
print(t1.dtype)
print(t1.device)
print(t1.requires_grad)
print(t1.size())
print(t1.shape)

torch.float32
cpu
False
torch.Size([3])
torch.Size([3])


In [3]:
t2 = torch.tensor([1, 2, 3], device='cpu')
print(t2.dtype)
print(t2.device)
print(t2.requires_grad)
print(t2.size())
print(t2.shape)

torch.int64
cpu
False
torch.Size([3])
torch.Size([3])


.Tensor는 데이터타입을 float형으로 바꿈

.tensor는 데이터타입을 그대로 유지시켜줌

In [4]:
a1 = torch.tensor(1)
print('shape : ', a1.shape, '\nndims : ', a1.ndim)

shape :  torch.Size([]) 
ndims :  0


In [5]:
a2 = torch.tensor([1])
print('shape : ', a2.shape, '\nndims : ', a2.ndim)

shape :  torch.Size([1]) 
ndims :  1


In [6]:
a3 = torch.tensor([1, 2, 3, 4, 5])
print('shape : ', a3.shape, '\nndims : ', a3.ndim)

shape :  torch.Size([5]) 
ndims :  1


In [7]:
a4 = torch.tensor([[1], [2], [3], [4], [5]])
print('shape : ', a4.shape, '\nndims : ', a4.ndim)

shape :  torch.Size([5, 1]) 
ndims :  2


In [8]:
a5 = torch.tensor([
    [1, 2],
    [3, 4],
    [5, 6]
])
print('shape : ', a5.shape, '\nndims : ', a5.ndim)

shape :  torch.Size([3, 2]) 
ndims :  2


In [9]:
a6 = torch.tensor([
    [[1], [2]],
    [[3], [4]],
    [[5], [6]]
])
print('shape : ', a6.shape, '\nndims : ', a6.ndim)

shape :  torch.Size([3, 2, 1]) 
ndims :  3


In [10]:
a7 = torch.tensor([
    [[[1], [2]]],
    [[[3], [4]]],
    [[[5], [6]]]
])
print('shape : ', a7.shape, '\nndims : ', a7.ndim)

shape :  torch.Size([3, 1, 2, 1]) 
ndims :  4


In [11]:
a8 = torch.tensor([
    [[[1, 2, 3], [2, 3, 4]]],
    [[[3, 1, 1], [4, 4, 5]]],
    [[[5, 6, 2], [6, 3, 1]]]
])
print('shape : ', a8.shape, '\nndims : ', a8.ndim)

shape :  torch.Size([3, 1, 2, 3]) 
ndims :  4


In [12]:
a9 = torch.tensor([
    [[[[1], [2], [3]], [[2], [3], [4]]]],
    [[[[3], [1], [1]], [[4], [4], [5]]]],
    [[[[5], [6], [2]], [[6], [3], [1]]]]
])
print('shape : ', a9.shape, '\nndims : ', a9.ndim)

shape :  torch.Size([3, 1, 2, 3, 1]) 
ndims :  5


In [13]:
a10 = torch.tensor([
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    ])
print('shape : ', a10.shape, '\nndims : ', a10.ndim)

shape :  torch.Size([4, 5]) 
ndims :  2


In [14]:
a11 = torch.tensor([
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    ])
print('shape : ', a11.shape, '\nndims : ', a11.ndim)

shape :  torch.Size([4, 1, 5]) 
ndims :  3


In [15]:
# a12 = torch.tensor([
#     [[[1, 2, 3], [4, 5]]],
#     [[[1, 2, 3], [4, 5]]],
#     [[[1, 2, 3], [4, 5]]],
#     [[[1, 2, 3], [4, 5]]],
#     ])
# print('shape : ', a11.shape, '\nndims : ', a11.ndim)  # runall이 오류에 막혀서 실행시킨 후 주석처리하였습니다.

a12 텐서에서는 같은 디멘션에서의 길이(원소의 개수)가 달라 에러가 발생한 모습

# b_tensor_initialization_copy

In [16]:
import torch
import numpy as np

In [17]:
l1 = [1, 2, 3]
t1 = torch.Tensor(l1)

l2 = [1, 2, 3]
t2 = torch.tensor(l2)

l3 = [1, 2, 3]
t3 = torch.as_tensor(l3)

l1[0] = 100
l2[0] = 100
l3[0] = 100

print(t1)
print(t2)
print(t3)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])


t1, t2, t3는 각각 l1, l2, l3를 copy하여 새로 생성한 객체이기 때문에 l1, l2, l3를 바꿔도 t1, t2, t3는 영향을 받지 않음

In [18]:
l4 = np.array([1, 2, 3])
t4 = torch.Tensor(l4)

l5 = np.array([1, 2, 3])
t5 = torch.tensor(l5)

l6 = np.array([1, 2, 3])
t6 = torch.as_tensor(l6)

l4[0] = 100
l5[0] = 100
l6[0] = 100

print(t4)
print(t5)
print(t6)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([100,   2,   3])


t4, t5도 l4, l5를 copy하여 생성한 객체이기 때문에 l4, l5를 바꿔도 t4, t5가 영향을 받지 않지만, numpy 배열을 as_tensor로 가져올 땐 l6객체를 공유하기 때문에
l6의 값을 바꾸면 t6의 값도 같이 바뀌게 됨

# c_tensor_initialization_constant_values

In [19]:
import torch

In [20]:
t1 = torch.ones(size=(5,))  # (5,) 크기의 텐서를 1로 가득 채움
t1_like = torch.ones_like(input=t1) # input 데이터의 크기와 모양만 가져와 1로 가득 채움
print('t1 : ', t1)
print('t1_like : ', t1_like)

l1 = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
l1_like = torch.ones_like(l1)
print('l1 : ', l1)
print('l1_like : ', l1_like)

t1 :  tensor([1., 1., 1., 1., 1.])
t1_like :  tensor([1., 1., 1., 1., 1.])
l1 :  tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
l1_like :  tensor([1, 1, 1, 1, 1, 1, 1, 1, 1])


l1_like가 입력으로 받은 l1의 값 자체는 무시하고 크기와 모양만 가져와 내부 값을 모두 1로 만든 모습

In [21]:
t2 = torch.zeros(size=(6,)) # (6,) 크기의 텐서를 0으로 가득 채움
t2_like = torch.zeros_like(input=t2) # input 데이터의 크기와 모양만 가져와 0으로 가득 채움
print('t2 : ', t2)
print('t2_like : ', t2_like)

l2 = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]])
l2_like = torch.zeros_like(l2)
print('l2 : ', l2)
print('l2_like : ', l2_like)

t2 :  tensor([0., 0., 0., 0., 0., 0.])
t2_like :  tensor([0., 0., 0., 0., 0., 0.])
l2 :  tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
l2_like :  tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]])


In [22]:
t3 = torch.empty(size=(4,)) # (4,) 크기의 텐서를 초기화되지 않은 값으로 가득 채움
t3_like = torch.empty_like(input=t3) # input 데이터의 크기와 모양을 가져와 빈값(0)으로 가득 채움. 해당 값들은 초기화되지 않은 값이기 때문에 사용전에 초기화를 해줘야함
print('t3 : ', t3)
print('t3_like : ', t3_like)

l3 = torch.tensor([1, 3, 2, 1, 5, 6, 1, 2])
l3_like = torch.empty_like(l3)
print('l3 : ', l3)
print('l3_like : ', l3_like)

t3 :  tensor([0., 0., 0., 0.])
t3_like :  tensor([0., 0., 0., 0.])
l3 :  tensor([1, 3, 2, 1, 5, 6, 1, 2])
l3_like :  tensor([0, 0, 0, 0, 0, 0, 0, 0])


In [23]:
t4 = torch.eye(n=3)
print(t4)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


torch.eye는 입력받는 n의 값에 따라 n*n 크기의 단위행렬을 생성해줌

# d_tensor_initialization_random_values

In [24]:
import torch

In [25]:
t1 = torch.randint(low=10, high=20, size=(1, 2)) # (1, 2) 사이즈의 텐서를 최소 10 최대 20 사이의 랜덤 int 값으로 채움
print(t1.dtype)
print(t1)

torch.int64
tensor([[13, 16]])


In [26]:
t2 = torch.rand(size=(1, 3)) # (1, 3) 사이즈의 텐서를 0에서 1사이의 랜덤한 실수 float 값으로 채움
print(t2.dtype)
print(t2)

torch.float32
tensor([[0.7060, 0.8836, 0.7397]])


In [27]:
t3 = torch.randn(size=(1, 3)) # (1, 3)사이즈의 텐서를 표준 정규 분포에서 평균이 0이고 표준편차가 1인 랜덤한 실수 float 값으로 채움
print(t3.dtype)
print(t3)

torch.float32
tensor([[1.3155, 1.1747, 2.8174]])


In [28]:
t4 = torch.normal(mean=10.0, std=1.0, size=(3, 2)) # (3, 2)사이즈의 텐서를 가우시안 정규분포 내에서 평균 10, 표준편차 1인 랜덤한 실수 float값으로 채움
print(t4.dtype)
print(t4)

torch.float32
tensor([[ 9.7326, 11.0743],
        [ 8.9923, 11.6500],
        [ 9.3798,  9.8218]])


In [29]:
t5 = torch.linspace(start=0.0, end=5.0, steps=3) # 0부터 5를 시작, 중간, 끝으로 3등분한 실수 float 값으로 텐서 생성
print(t5.dtype)
print(t5)

torch.float32
tensor([0.0000, 2.5000, 5.0000])


In [30]:
t6 = torch.arange(5) # 0에서 4까지의 인트값으로 텐서 생성
print(t6.dtype)
print(t6)

torch.int64
tensor([0, 1, 2, 3, 4])


In [31]:
torch.manual_seed(1729) # 랜덤값이 이 시드에 의해 결정되어 시드를 정해주면 랜덤값이 고정됨
random1 = torch.rand(2, 3)
print(random1)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


In [32]:
random2 = torch.rand(2, 3)
print(random2)

tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


In [33]:
torch.manual_seed(1729) # 랜덤값이 이 시드에 의해 결정되어 시드를 정해주면 랜덤값이 고정됨
random3 = torch.rand(2, 3)
print(random3)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


In [34]:
random4 = torch.rand(2, 3)
print(random4)

tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


# e_tensor_type_conversion

In [35]:
import torch

In [36]:
a = torch.ones((2, 3))
print('type : ', a.dtype) # ones의 data type은 float형이 default
print('a : ', a)

type :  torch.float32
a :  tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [37]:
b = torch.ones((2, 3), dtype=torch.int16) # dtype을 인수로 넣어 형태를 정해줄 수 있음
print(b) # 결과에 dtype도 나옴

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)


In [38]:
d = b.to(torch.int32) # b 그대로 가져와서 int32형으로 객체 d 생성
print(d)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)


In [39]:
double_d = torch.ones(10, 2, dtype=torch.double)
short_e = torch.tensor([[1, 2]], dtype=torch.short)
print('double_d : ', double_d)
print('short_e : ', short_e)

double_d :  tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)
short_e :  tensor([[1, 2]], dtype=torch.int16)


In [40]:
double_d = torch.zeros(10, 2).double()
short_e = torch.ones(10, 2).short()
print('double_d : ', double_d)
print('short_e : ', short_e)

double_d :  tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)
short_e :  tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]], dtype=torch.int16)


In [41]:
double_d = torch.zeros(10, 2).to(torch.double)
short_e = torch.ones(10, 2).to(dtype=torch.short)
print('double_d : ', double_d)
print('short_e : ', short_e)

double_d :  tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)
short_e :  tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]], dtype=torch.int16)


In [42]:
double_d = torch.zeros(10, 2).type(torch.double)
short_e = torch.ones(10, 2).type(dtype=torch.short)
print('double_d : ', double_d)
print('short_e : ', short_e)

double_d :  tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)
short_e :  tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]], dtype=torch.int16)


dtype을 인수로 지정하거나 여러 메서드를 이용하여 전체 데이터에 타입을 브로드캐스트시킬 수 있음

In [43]:
double_f = torch.rand(5, dtype=torch.double) # 5개의 double형 랜덤값(0~1)으로 이뤄진 텐서 생성
short_g = double_f.to(torch.short) # double_f가져와서 short형으로 텐서 생성
print((double_f*short_g).dtype) # 결과 : double * short 하니 결과값이 double형으로 나옴

torch.float64


# f_tensor_operations

In [44]:
t1 = torch.ones(size=(2, 3))
t2 = torch.ones(size=(2, 3))
t3 = torch.add(t1, t2)  # .add(a, b)는 a와 b텐서의 합을 구하는데 각 두 텐서의 사이즈가 다르면 오류 발생
t4 = t1 + t2
print('t3 : ', t3)
print('t4 : ', t4)

t3 :  tensor([[2., 2., 2.],
        [2., 2., 2.]])
t4 :  tensor([[2., 2., 2.],
        [2., 2., 2.]])


In [45]:
t5 = torch.sub(t1, t2) # .sub(a, b)는 a와 b텐서의 차를 구하는데 두 텐서의 사이즈가 다르면 오류 발생
t6 = t1 - t2
print('t5 : ', t5)
print('t6 : ', t6)

t5 :  tensor([[0., 0., 0.],
        [0., 0., 0.]])
t6 :  tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [46]:
t7 = torch.mul(t1, t2) # .mul(a, b)는 a와 b의 곱을 구하는데 두 텐서의 사이즈가 다르면 오류 발생
t8 = t1 * t2
print('t7 : ', t7)
print('t8 : ', t8)

t7 :  tensor([[1., 1., 1.],
        [1., 1., 1.]])
t8 :  tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [47]:
t9 = torch.div(t1, t2) # .div(a, b)는 a를 b로 나눈 몫을 구하는데 두 텐서의 사이즈가 다르면 오류 발생
t10 = t1 / t2
print('t9 : ', t9)
print('t10 : ', t10)

t9 :  tensor([[1., 1., 1.],
        [1., 1., 1.]])
t10 :  tensor([[1., 1., 1.],
        [1., 1., 1.]])


# g_tensor_operations_mm

In [48]:
import torch

In [49]:
t1 = torch.dot(
    torch.tensor([2, 3]), torch.tensor([2, 1]) # [a1, b1], [a2, b2]의 dot product연산 결과는 a1*b1 + a2*b2
)
print(t1, t1.size()) # 연산 결과로 텐서들을 하나의 값으로 만들었기 때문에 결과값은 스칼라값이 됨

tensor(7) torch.Size([])


In [50]:
t2 = torch.randn(2, 3)
t3 = torch.randn(3, 2)
t4 = torch.mm(t2, t3) # (a, b), (c, d)사이즈의 matmul 연산 결과는 (a, d)사이즈가 됨
print(t4, t4.size()) # 곱셈 시 브로드캐스트를 지원하지 않으므로 b와 c의 값을 맞춰줘야함

tensor([[-1.1766, -0.3342],
        [-3.0611, -0.5943]]) torch.Size([2, 2])


In [51]:
t5 = torch.randn(10, 3, 4)
t6 = torch.randn(10, 4, 5)
t7 = torch.bmm(t5, t6) # 인수 가장 앞의 배치값을 제외하면 mm메서드와 사용법이 동일
print(t7.size()) # 연산 : (a, b, c), (a, c, d) 결과 : (a, b, d)

torch.Size([10, 3, 5])


# h_tensor_operations_matmul

In [52]:
import torch

In [53]:
t1 = torch.randn(3) # vector
t2 = torch.randn(3) # vector
print(torch.matmul(t1, t2).size()) # Vector와 Vector의 곱은 두 벡터의 dot product 결과와 같음 = 스칼라

torch.Size([])


In [54]:
t3 = torch.randn(3, 4) # matrix
t4 = torch.randn(4) # vector
print(torch.matmul(t3, t4).size()) # matrix(a, b)와 vector(b)의 곱은 broadcast dot을 통해 (a)사이즈의 텐서만 남음

torch.Size([3])


In [55]:
t5 = torch.randn(10, 3, 4) # batched matrix
t6 = torch.randn(4) # vector
print(torch.matmul(t5, t6).size()) # batched matrix는 matrix에 batch가 붙은걸 제외하면 matrix와 vector간의 연산과 크게 다르지 않음

torch.Size([10, 3])


In [56]:
t7 = torch.randn(10, 3, 4) # batched matrix
t8 = torch.randn(10, 4, 5) # batched matrix
print(torch.matmul(t7, t8).size()) # batched matrix간의 matmul연산도 위에서 했던것 처럼 (a, b, c), (a, c, d)이면 (a, b, d)로 나옴

torch.Size([10, 3, 5])


In [57]:
t9 = torch.randn(10, 3, 4) # batched matrix
t10 = torch.randn(4, 5) # matrix
print(torch.matmul(t9, t10).size()) # batched와 그냥 matrix를 matmul해주면 batch는 그대로 두고 뒤의 matrix끼리 dot연산

torch.Size([10, 3, 5])


# i_tensor_broadcasting

In [58]:
import torch

In [59]:
t1 = torch.tensor([1.0, 2.0, 3.0])
t2 = 2.0
print(t1 * t2) # broadcasting해줘서 텐서 전체에 * 2

tensor([2., 4., 6.])


In [60]:
t3 = torch.tensor([[0, 1], [2, 4], [10, 10]])
t4 = torch.tensor([4, 5])
print('t3_size : ', t3.size())
print('t3 - t4 size : ', (t3 - t4).size())
print('t3 - t4 :', t3 - t4)
# 차도 broadcasting해서 t3의 size가 유지됨

t3_size :  torch.Size([3, 2])
t3 - t4 size :  torch.Size([3, 2])
t3 - t4 : tensor([[-4, -4],
        [-2, -1],
        [ 6,  5]])


In [61]:
t5 = torch.tensor([[1., 2.], [3., 4.]])
print(t5 + 2.0)
print(t5 - 2.0)
print(t5 * 2.0)
print(t5 / 2.0)
# 사칙연산 모두 broadcast된 모습

tensor([[3., 4.],
        [5., 6.]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


In [62]:
def normalize(x):
    return x / 255

In [63]:
t6 = torch.randn(3, 28, 28)
print(normalize(t6).size()) # normalization은 사용자가 데이터를 원하는 범위로 제한하기 위해 사용함 ex) 0~1사이

torch.Size([3, 28, 28])


In [64]:
t7 = torch.tensor([[1, 2], [0, 3]]) # size : (2, 2)
t8 = torch.tensor([[3, 1]]) # size : (1, 2)
t9 = torch.tensor([[5], [2]]) # size : (2, 1)
t10 = torch.tensor([7]) # size : (1)

print(t7 + t8)
print(t7 + t9)
print(t8 + t9)
print(t7 + t10)

tensor([[4, 3],
        [3, 4]])
tensor([[6, 7],
        [2, 5]])
tensor([[8, 6],
        [5, 3]])
tensor([[ 8,  9],
        [ 7, 10]])


In [65]:
t11 = torch.ones(4, 3, 2)
t12 = t11 * torch.rand(3, 2)# 텐서끼리 곱할 때 사이즈를 뒤로 붙여서 계산한다고 봐야함 ex)   (4, 3, 2)
print(t12.shape) #                                                           (   3, 2)

torch.Size([4, 3, 2])


In [66]:
t13 = torch.ones(4, 3, 2)   # 위와 같이 뒤로 붙여서 계산하며, 텐서의 곱에서는 같은 dim의 위치끼리 size가 같아야함
t14 = t13 * torch.rand(3, 1)
print(t14.shape)

torch.Size([4, 3, 2])


In [67]:
t15 = torch.ones(4, 3, 2)
t16 = t15 * torch.rand(1, 2)
print(t16.shape)

torch.Size([4, 3, 2])


In [68]:
t17 = torch.ones(5, 3, 4, 1)
t18 = torch.rand(3, 1, 1)
print((t17 + t18).size())

torch.Size([5, 3, 4, 1])


In [69]:
t19 = torch.empty(5, 1, 4, 1)
t20 = torch.empty(3, 1, 1)
print((t19 + t20).size())

torch.Size([5, 3, 4, 1])


In [70]:
t21 = torch.empty(1)
t22 = torch.empty(3, 1, 7)
print((t21 + t22).size())

torch.Size([3, 1, 7])


In [71]:
t23 = torch.ones(3, 3, 3)
t24 = torch.ones(3, 1, 3)
print((t23 + t24).size())

torch.Size([3, 3, 3])


In [72]:
# t25 = torch.empty(5, 2, 4, 1) # 차원의 수가 더 많은 텐서의 size가 적은 텐서보다 커야함
# t26 = torch.empty(3, 1, 1) # (2, 4, 1) vs (3, 1, 1)에서 앞의 텐서가 2로 더 작아서 에러 발생
# print((t25 + t26).size())

In [73]:
t27 = torch.ones(4) * 5
print(t27) # 5를 tensor(4)에 broadcasting

tensor([5., 5., 5., 5.])


In [74]:
t28 = torch.pow(t27, 2)
print(t28) # 제곱연산도 broadcasting

tensor([25., 25., 25., 25.])


In [75]:
exp = torch.arange(1., 5.) # torch.tensor([1., 2., 3., 4.])
a = torch.arange(1., 5.) # torch.tensor([1., 2., 3., 4.])
t29 = torch.pow(a, exp) # 순서에 맞게 exp가 밑, a가 지수
print(t29)

tensor([  1.,   4.,  27., 256.])


# j_tensor_indexing_slicing

In [76]:
import torch

In [77]:
x = torch.tensor(
    [[0, 1, 2, 3, 4],
     [5, 6, 7, 8, 9],
     [10, 11, 12, 13, 14]]
)

print(x[1]) # (3, 5)에서 인덱스를 하나만 지정해줬으므로 앞의 인덱스 1일 때 출력
print(x[:, 1]) # 세로 인덱스 1일 때 출력
print(x[1, 2]) # (3, 5)에 맞춰 각각 인덱스 1, 2일 때 출력
print(x[:, -1]) # 세로인덱스인데 -1이므로 뒤에서 출력

tensor([5, 6, 7, 8, 9])
tensor([ 1,  6, 11])
tensor(7)
tensor([ 4,  9, 14])


In [78]:
print(x[1:]) # (3, 5)에서 앞의 인덱스 1부터 출력
print(x[1:, 3:]) # 앞의 인덱스는 1부터, 뒤의 인덱스는 3부터 출력

tensor([[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])
tensor([[ 8,  9],
        [13, 14]])


In [79]:
y = torch.zeros((6, 6))
y[1:4, 2] = 1 # 1:4이므로 (6, 6)에서 앞의 인덱스 1, 2, 3인 경우이고, 세로 인덱스 2인 값들 1로 만듬
print(y)

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])


In [80]:
print(y[1:4, 1:4]) # 가로 세로 인덱스 1, 2, 3만 뽑아서 출력

tensor([[0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.]])


In [81]:
z = torch.tensor(
    [[1, 2, 3, 4],
     [2, 3, 4, 5],
     [5, 6, 7, 8]]
)
print(z[:2])
print(z[1:, 1:3])
print(z[:, 1:])

tensor([[1, 2, 3, 4],
        [2, 3, 4, 5]])
tensor([[3, 4],
        [6, 7]])
tensor([[2, 3, 4],
        [3, 4, 5],
        [6, 7, 8]])


In [82]:
z[1:, 1:3] = 0
print(z)

tensor([[1, 2, 3, 4],
        [2, 0, 0, 5],
        [5, 0, 0, 8]])


# k_tensor_reshaping

In [83]:
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = t1.view(3, 2)
t3 = t1.reshape(1, 6) # view나 reshape은 모양 바꾸고 copy만들어서 생성
print(t2)
print(t3)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3, 4, 5, 6]])


In [84]:
t4 = torch.arange(8).view(2, 4) # 0~7까지 텐서 만들고 (2, 4)사이즈로 생성
t5 = torch.arange(6).view(2, 3) # 0~5까지 텐서 만들고 (2, 3)사이즈로 생성
print(t4)
print(t5)

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[0, 1, 2],
        [3, 4, 5]])


In [85]:
t6 = torch.tensor([[[1], [2], [3]]]) # (1, 3, 1)
t7 = t6.squeeze() # size = 1 인 dimension 모두 삭제 >>(3)
t8 = t6.squeeze(0) # 인덱스가 0인 dimension 삭제 >> (3, 1)
print(t7)
print(t8)

tensor([1, 2, 3])
tensor([[1],
        [2],
        [3]])


In [86]:
t9 = torch.tensor([1, 2, 3]) # (3, )
t10 = t9.unsqueeze(1) # 인덱스 1인 dimension 추가 >> (3, 1)
print(t10)

tensor([[1],
        [2],
        [3]])


In [87]:
t11 = torch.tensor( # (2, 3)
  [[1, 2, 3],
   [4, 5, 6]]
)
t12 = t11.unsqueeze(1)  # 인덱스 1인 dimension 추가 >> (2, 1, 3)
print(t12, t12.shape)

tensor([[[1, 2, 3]],

        [[4, 5, 6]]]) torch.Size([2, 1, 3])


In [88]:
t13 = torch.tensor([[1, 2, 3], [4, 5, 6]]) # (2, 3)
t14 = t13.flatten() # []로 묶여있던 텐서들을 한줄(?)로 풀어줌 >> (6, )
print(t14)

tensor([1, 2, 3, 4, 5, 6])


In [89]:
t15 = torch.tensor([[[1, 2],
                     [3, 4]],
                    [[5, 6],
                     [7, 8]]]) # (2, 2, 2)
t16 = torch.flatten(t15) # >>(6, )
t17 = torch.flatten(t15, start_dim=1) # 인덱스 1인 dimension부터 flatten >> (2, 4)
print(t16)
print(t17)

tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [90]:
t18 = torch.randn(2, 3, 5)
print('shape : ', t18.shape)  # (2, 3, 5)
print('permute : ', torch.permute(t18, (2, 0, 1)).shape) # 순서 바꾸기로, 2번째 인수인 (2, 0, 1)은 각각 원래 dimension의 순서를 (2번째, 0번째, 1번째)로 바꾸라는 얘기임 >> (5, 2, 3)

shape :  torch.Size([2, 3, 5])
permute :  torch.Size([5, 2, 3])


In [91]:
t19 = torch.tensor([[1, 2, 3], [4, 5, 6]]) # (2, 3)
t20 = torch.permute(t19, dims=(0, 1))  # 0번째, 1번째이니 (2, 3)그대로 유지
t21 = torch.permute(t19, dims=(1, 0))  # 1번째, 0번째이니 (3, 2)로 변경
print(t20)
print(t21)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [92]:
t22 = torch.transpose(t19, 0, 1) # t19의 0번째와 1번째 인덱스 교환이니 (3, 2)로 변경
print(t22)

tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [93]:
t23 = torch.t(t19) # 2d텐서 0, 1 인덱스 반전시켜 (3, 2)
print(t23)

tensor([[1, 4],
        [2, 5],
        [3, 6]])


# l_tensor_concat

In [94]:
t1 = torch.zeros([2, 1, 3])
t2 = torch.zeros([2, 3, 3])
t3 = torch.zeros([2, 2, 3])

t4 = torch.cat([t1, t2, t3], dim=1) # dim 인수에 들어가있는 dimension을 기준으로 텐서 통합
print(t4.shape)

torch.Size([2, 6, 3])


In [95]:
t5 = torch.arange(0, 3)  # [0, 1, 2]
t6 = torch.arange(3, 8)  # [3, 4, 5, 6, 7]

t7 = torch.cat((t5, t6), dim=0) # >> [0, 1, 2, 3, 4, 5, 6, 7]
print(t7.shape) # (8)
print(t7)

torch.Size([8])
tensor([0, 1, 2, 3, 4, 5, 6, 7])


In [96]:
t8 = torch.arange(0, 6).reshape(2, 3)  # [[0, 1, 2], [3, 4, 5]]
t9 = torch.arange(6, 12).reshape(2, 3)  # [[6, 7, 8],[9, 10, 11]]

# 2차원 텐서간 병합
t10 = torch.cat((t8, t9), dim=0) # dim = 0 기준으로 통합 >> [[0~2], [3~5], [6~8], [9~11]]
print(t10.size())  # (4, 3)
print(t10)

t11 = torch.cat((t8, t9), dim=1) # dim = 1을 기준으로 통합 >> [[0~2, 6~8], [3~5, 9~11]]
print(t11.size())  # (2, 6)
print(t11)

torch.Size([4, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
torch.Size([2, 6])
tensor([[ 0,  1,  2,  6,  7,  8],
        [ 3,  4,  5,  9, 10, 11]])


In [97]:
t12 = torch.arange(0, 6).reshape(2, 3)  # [[0, 1, 2], [3, 4, 5]]
t13 = torch.arange(6, 12).reshape(2, 3)  # [[6, 7, 8],[9, 10, 11]]
t14 = torch.arange(12, 18).reshape(2, 3)  # [[12, 13, 14],[15, 16, 17]]

t15 = torch.cat((t12, t13, t14), dim=0) # dim = 0 기준 통합
print(t15.size())  # (6, 3)
print(t15)

t16 = torch.cat((t12, t13, t14), dim=1) # dim = 1 기준으로 통합
print(t16.size())  # (2, 9)
print(t16)

torch.Size([6, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])
torch.Size([2, 9])
tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
        [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])


In [98]:
t17 = torch.arange(0, 6).reshape(1, 2, 3)  # [[[0, 1, 2], [3, 4, 5]]]
t18 = torch.arange(6, 12).reshape(1, 2, 3)  # [[[6, 7, 8], [9, 10, 11]]]

t19 = torch.cat((t17, t18), dim=0) # dim = 0 기준 통합
print(t19.size())  # (2, 2, 3)
print(t19)

t20 = torch.cat((t17, t18), dim=1) # dim = 1 기준 통합
print(t20.size())  # (1, 4, 3)
print(t20)

t21 = torch.cat((t17, t18), dim=2) # dim = 2 기준 통합
print(t21.size())  # (1, 2, 6)
print(t21)

torch.Size([2, 2, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 4, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 2, 6])
tensor([[[ 0,  1,  2,  6,  7,  8],
         [ 3,  4,  5,  9, 10, 11]]])


# m_tensor_stacking

In [99]:
import torch

In [100]:
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]]) # (2, 3)
t2 = torch.tensor([[7, 8, 9], [10, 11, 12]]) # (2, 3)

t3 = torch.stack([t1, t2], dim=0) # dim = 0 차원을 새로 추가하고 기준으로 삼아 통합
t4 = torch.cat([t1.unsqueeze(dim=0), t2.unsqueeze(dim=0)], dim=0) # 각 텐서에 dim = 0 기준으로 unsqeeze시키고 통합하면 stack과 같은 결과가 나옴
print(t3.shape, t3.equal(t4))

torch.Size([2, 2, 3]) True


In [101]:
t5 = torch.stack([t1, t2], dim=1) # dim = 1 기준 통합
t6 = torch.cat([t1.unsqueeze(dim=1), t2.unsqueeze(dim=1)], dim=1) # 위와 같은데 dim만 1을 기준으로
print(t5.shape, t5.equal(t6))

t7 = torch.stack([t1, t2], dim=2) # dim = 2 기준 통합
t8 = torch.cat([t1.unsqueeze(dim=2), t2.unsqueeze(dim=2)], dim=2) # 위와 같은데 dim만 2를 기준으로
print(t7.shape, t7.equal(t8))

torch.Size([2, 2, 3]) True
torch.Size([2, 3, 2]) True


In [102]:
t9 = torch.arange(0, 3)  # [0, 1, 2] > (3)
t10 = torch.arange(3, 6)  # [3, 4, 5] > (3)
print(t9.size(), t10.size())

torch.Size([3]) torch.Size([3])


In [103]:
t11 = torch.stack((t9, t10), dim=0) # dim = 0 기준 통합
print(t11.size())  # (2, 3)
print(t11)

torch.Size([2, 3])
tensor([[0, 1, 2],
        [3, 4, 5]])


In [104]:
t12 = torch.cat((t9.unsqueeze(0), t10.unsqueeze(0)), dim=0)
print(t11.equal(t12))

True


In [105]:
t13 = torch.stack((t9, t10), dim=1) # dim = 1 기준 통합
print(t13.size())  # (3,2)
print(t13)

torch.Size([3, 2])
tensor([[0, 3],
        [1, 4],
        [2, 5]])


In [106]:
t14 = torch.cat((t9.unsqueeze(1), t10.unsqueeze(1)), dim=1)
print(t13.equal(t14))

True


# n_tensor_vstack_hstack

In [107]:
t1 = torch.tensor([1, 2, 3]) # (3)
t2 = torch.tensor([4, 5, 6]) # (3)
t3 = torch.vstack((t1, t2)) # vertically stack > row wise > (column 수가 같아야 함)
print(t3)
print(t3.shape)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])


In [108]:
t4 = torch.tensor([[1], [2], [3]]) # (3, 1)
t5 = torch.tensor([[4], [5], [6]]) # (3, 1)
t6 = torch.vstack((t4, t5))
print(t6)
print(t6.shape)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])
torch.Size([6, 1])


In [109]:
t7 = torch.tensor([  # (2, 2, 3)
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])

t8 = torch.tensor([ # (2, 2, 3)
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])

t9 = torch.vstack([t7, t8]) # vertically stack >> (4, 2, 3)
print(t9.shape)
print(t9)

torch.Size([4, 2, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]])


In [110]:
t10 = torch.tensor([1, 2, 3]) # (3)
t11 = torch.tensor([4, 5, 6]) # (3)
t12 = torch.hstack((t10, t11)) # horizontally stack > column wise > (row 수가 같아야 함)
print(t12)

tensor([1, 2, 3, 4, 5, 6])


In [111]:
t13 = torch.tensor([[1], [2], [3]]) # (3, 1)
t14 = torch.tensor([[4], [5], [6]]) # (3, 1)
t15 = torch.hstack((t13, t14)) # horizontally stack >> (3, 2)
print(t15)

tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [112]:
t16 = torch.tensor([ # (2, 2, 3)
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])

t17 = torch.tensor([ # (2, 2, 3)
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])

t18 = torch.hstack([t16, t17]) # horizontally stack >> (2, 4, 3)
print(t18.shape)
print(t18)

torch.Size([2, 4, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [13, 14, 15],
         [16, 17, 18]],

        [[ 7,  8,  9],
         [10, 11, 12],
         [19, 20, 21],
         [22, 23, 24]]])


# 숙제 후기

## 수업으로만 들었을 때와 직접 코드를 쳐봤을 때 이해의 깊이가 다르다는 것을 깨달았습니다. 눈으로만 봤을 때는 코드의 결과가 이해가 잘 안가는 경우가 조금 있었는데, 손으로 직접 코드를 쳐보니 코드를 완성해가는 과정에서 계속해서 지금 치고있는 코드의 결과가 어떻게 될지에 대해서 생각하게 되고, 다음에 같은 코드를 쳤을 때 치는 과정에서 정답이 보이기 시작하는 경지에 다다랐습니다. 처음에는 숙제가 조금 많다는 생각이 들었지만, 끝나고 나니 오히려 많았기 때문에 더욱 숙달될 수 있었다고 생각합니다. 감사합니다!!

### 각 코드를 쳐보며 나왔던 기술적 사항들이나 고찰, 왜 그렇게 나오는가에 대한 생각들을 주석에 달아놓았습니다.